export const GETNAVERSSAGA = "GETNAVERSSAGA";
export const GETNAVERBYIDSAGA = "GETNAVERBYIDSAGA";
export const POSTNAVERSSAGA = "POSTNAVERSSAGA";
export const PUTNAVERSAGA = "PUTNAVERSAGA";
export const DELETENAVERSAGA = "DELETENAVERSAGA";

export const GETNAVERS = "GETNAVERS";
export const GETNAVERBYID = "GETNAVERBYID";
export const POSTNAVERS = "POSTNAVERS";
export const PUTNAVER = "PUTNAVER";
export const DELETENAVER = "DELETENAVER";
